import type { Metadata } from "next";
import { poppins, fraunces } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${fraunces.variable} font-body antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
