// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * DayTimeResponse
 */
export const zDayTimeResponse = z.object({
    id: z.int(),
    day: z.string(),
    startTimeHhmm: z.string(),
    endTimeHhmm: z.string(),
    leclabId: z.int()
});

/**
 * LecLabType
 */
export const zLecLabType = z.enum(['lecture', 'laboratory']);

/**
 * Status
 */
export const zStatus = z.enum(['found', 'foundn\'t']);

/**
 * RatingResponse
 */
export const zRatingResponse = z.object({
    prof: z.string(),
    score: z.number(),
    avg: z.number(),
    nRating: z.int(),
    takeAgain: z.int(),
    difficulty: z.number(),
    status: zStatus,
    pId: z.union([
        z.string(),
        z.null()
    ])
});

/**
 * LecLabResponse
 */
export const zLecLabResponse = z.object({
    id: z.int(),
    title: z.string(),
    type: z.union([
        zLecLabType,
        z.null()
    ]),
    sectionId: z.int(),
    prof: z.string(),
    rating: z.union([
        zRatingResponse,
        z.null()
    ]),
    dayTimes: z.array(zDayTimeResponse)
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zViewData = z.array(z.record(z.string(), z.array(z.int())));

/**
 * SectionResponse
 */
export const zSectionResponse = z.object({
    id: z.int(),
    course: z.string(),
    section: z.string(),
    domain: z.string(),
    code: z.string(),
    title: z.string(),
    leclabs: z.array(zLecLabResponse),
    more: z.string(),
    viewData: zViewData
});

export const zGetAllSectionsAllGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get All Sections All Get
 *
 * Successful Response
 */
export const zGetAllSectionsAllGetResponse = z.array(zSectionResponse);

export const zGetSectionsSectionsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        q: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        course: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        domain: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        code: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        title: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        teacher: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        min_rating: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        max_rating: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        min_score: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        max_score: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        days_off: z.optional(z.union([
            z.string().regex(/^[MWTRF]{1,5}$/),
            z.null()
        ])),
        time_start: z.optional(z.union([
            z.string().regex(/^\d{4}$/),
            z.null()
        ])),
        time_end: z.optional(z.union([
            z.string().regex(/^\d{4}$/),
            z.null()
        ])),
        blended: z.optional(z.boolean()).default(false),
        honours: z.optional(z.boolean()).default(false),
        limit: z.optional(z.union([
            z.int().gte(1).lte(500),
            z.null()
        ])),
        offset: z.optional(z.int().gte(0)).default(0)
    }))
});

/**
 * Response Get Sections Sections  Get
 *
 * Successful Response
 */
export const zGetSectionsSectionsGetResponse = z.array(zSectionResponse);

export const zGetManySectionsPostData = z.object({
    body: z.array(z.int()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get Many Sections  Post
 *
 * Successful Response
 */
export const zGetManySectionsPostResponse = z.array(zSectionResponse);

export const zGetSectionSectionsSectionIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        section_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetSectionSectionsSectionIdGetResponse = zSectionResponse;

export const zRootGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zHealthHealthGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetRatingsRatingsProfGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        prof: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetRatingsRatingsProfGetResponse = zRatingResponse;

export const zGetLeclabLeclabSectionIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        section_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Response Get Leclab Leclab  Section Id  Get
 *
 * Successful Response
 */
export const zGetLeclabLeclabSectionIdGetResponse = z.array(zLecLabResponse);
