// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetLeclabLeclabSectionIdGetData, GetLeclabLeclabSectionIdGetErrors, GetLeclabLeclabSectionIdGetResponses, GetManySectionsPostData, GetManySectionsPostErrors, GetManySectionsPostResponses, GetRatingsRatingsProfGetData, GetRatingsRatingsProfGetErrors, GetRatingsRatingsProfGetResponses, GetSectionSectionsSectionIdGetData, GetSectionSectionsSectionIdGetErrors, GetSectionSectionsSectionIdGetResponses, GetSectionsSectionsGetData, GetSectionsSectionsGetErrors, GetSectionsSectionsGetResponses, HealthHealthGetData, HealthHealthGetResponses, RootGetData, RootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Sections
 */
export const getSectionsSectionsGet = <ThrowOnError extends boolean = false>(options?: Options<GetSectionsSectionsGetData, ThrowOnError>) => (options?.client ?? client).get<GetSectionsSectionsGetResponses, GetSectionsSectionsGetErrors, ThrowOnError>({ url: '/sections/', ...options });

/**
 * Get Many
 */
export const getManySectionsPost = <ThrowOnError extends boolean = false>(options: Options<GetManySectionsPostData, ThrowOnError>) => (options.client ?? client).post<GetManySectionsPostResponses, GetManySectionsPostErrors, ThrowOnError>({
    url: '/sections/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Section
 */
export const getSectionSectionsSectionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSectionSectionsSectionIdGetData, ThrowOnError>) => (options.client ?? client).get<GetSectionSectionsSectionIdGetResponses, GetSectionSectionsSectionIdGetErrors, ThrowOnError>({ url: '/sections/{section_id}', ...options });

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get Ratings
 */
export const getRatingsRatingsProfGet = <ThrowOnError extends boolean = false>(options: Options<GetRatingsRatingsProfGetData, ThrowOnError>) => (options.client ?? client).get<GetRatingsRatingsProfGetResponses, GetRatingsRatingsProfGetErrors, ThrowOnError>({ url: '/ratings/{prof}', ...options });

/**
 * Get Leclab
 */
export const getLeclabLeclabSectionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetLeclabLeclabSectionIdGetData, ThrowOnError>) => (options.client ?? client).get<GetLeclabLeclabSectionIdGetResponses, GetLeclabLeclabSectionIdGetErrors, ThrowOnError>({ url: '/leclab/{section_id}', ...options });
