// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * DayTimeResponse
 */
export type DayTimeResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Day
     */
    day: string;
    /**
     * Starttimehhmm
     */
    startTimeHhmm: string;
    /**
     * Endtimehhmm
     */
    endTimeHhmm: string;
    /**
     * Leclabid
     */
    leclabId: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LecLabResponse
 */
export type LecLabResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    type: LecLabType | null;
    /**
     * Sectionid
     */
    sectionId: number;
    /**
     * Prof
     */
    prof: string;
    rating: RatingResponse | null;
    /**
     * Daytimes
     */
    dayTimes: Array<DayTimeResponse>;
};

/**
 * LecLabType
 */
export type LecLabType = 'lecture' | 'laboratory';

/**
 * RatingResponse
 */
export type RatingResponse = {
    /**
     * Prof
     */
    prof: string;
    /**
     * Score
     */
    score: number;
    /**
     * Avg
     */
    avg: number;
    /**
     * Nrating
     */
    nRating: number;
    /**
     * Takeagain
     */
    takeAgain: number;
    /**
     * Difficulty
     */
    difficulty: number;
    status: Status;
    /**
     * Pid
     */
    pId: string | null;
};

/**
 * SectionResponse
 */
export type SectionResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Course
     */
    course: string;
    /**
     * Section
     */
    section: string;
    /**
     * Domain
     */
    domain: string;
    /**
     * Code
     */
    code: string;
    /**
     * Title
     */
    title: string;
    /**
     * Leclabs
     */
    leclabs: Array<LecLabResponse>;
    /**
     * More
     */
    more: string;
    viewData: ViewData;
};

/**
 * Status
 */
export type Status = 'found' | 'foundn\'t';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ViewData = Array<{
    [key: string]: Array<number>;
}>;

export type GetSectionsSectionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Course
         */
        course?: string | null;
        /**
         * Domain
         */
        domain?: string | null;
        /**
         * Code
         */
        code?: string | null;
        /**
         * Title
         */
        title?: string | null;
        /**
         * Teacher
         */
        teacher?: string | null;
        /**
         * Min Rating
         */
        min_rating?: number | null;
        /**
         * Max Rating
         */
        max_rating?: number | null;
        /**
         * Min Score
         */
        min_score?: number | null;
        /**
         * Max Score
         */
        max_score?: number | null;
        /**
         * Days Off
         */
        days_off?: string | null;
        /**
         * Time Start
         */
        time_start?: string | null;
        /**
         * Time End
         */
        time_end?: string | null;
        /**
         * Blended
         */
        blended?: boolean;
        /**
         * Honours
         */
        honours?: boolean;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/sections/';
};

export type GetSectionsSectionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSectionsSectionsGetError = GetSectionsSectionsGetErrors[keyof GetSectionsSectionsGetErrors];

export type GetSectionsSectionsGetResponses = {
    /**
     * Response Get Sections Sections  Get
     *
     * Successful Response
     */
    200: Array<SectionResponse>;
};

export type GetSectionsSectionsGetResponse = GetSectionsSectionsGetResponses[keyof GetSectionsSectionsGetResponses];

export type GetManySectionsPostData = {
    /**
     * Ids
     */
    body: Array<number>;
    path?: never;
    query?: never;
    url: '/sections/';
};

export type GetManySectionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetManySectionsPostError = GetManySectionsPostErrors[keyof GetManySectionsPostErrors];

export type GetManySectionsPostResponses = {
    /**
     * Response Get Many Sections  Post
     *
     * Successful Response
     */
    200: Array<SectionResponse>;
};

export type GetManySectionsPostResponse = GetManySectionsPostResponses[keyof GetManySectionsPostResponses];

export type GetSectionSectionsSectionIdGetData = {
    body?: never;
    path: {
        /**
         * Section Id
         */
        section_id: number;
    };
    query?: never;
    url: '/sections/{section_id}';
};

export type GetSectionSectionsSectionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSectionSectionsSectionIdGetError = GetSectionSectionsSectionIdGetErrors[keyof GetSectionSectionsSectionIdGetErrors];

export type GetSectionSectionsSectionIdGetResponses = {
    /**
     * Successful Response
     */
    200: SectionResponse;
};

export type GetSectionSectionsSectionIdGetResponse = GetSectionSectionsSectionIdGetResponses[keyof GetSectionSectionsSectionIdGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRatingsRatingsProfGetData = {
    body?: never;
    path: {
        /**
         * Prof
         */
        prof: string;
    };
    query?: never;
    url: '/ratings/{prof}';
};

export type GetRatingsRatingsProfGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRatingsRatingsProfGetError = GetRatingsRatingsProfGetErrors[keyof GetRatingsRatingsProfGetErrors];

export type GetRatingsRatingsProfGetResponses = {
    /**
     * Successful Response
     */
    200: RatingResponse;
};

export type GetRatingsRatingsProfGetResponse = GetRatingsRatingsProfGetResponses[keyof GetRatingsRatingsProfGetResponses];

export type GetLeclabLeclabSectionIdGetData = {
    body?: never;
    path: {
        /**
         * Section Id
         */
        section_id: number;
    };
    query?: never;
    url: '/leclab/{section_id}';
};

export type GetLeclabLeclabSectionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLeclabLeclabSectionIdGetError = GetLeclabLeclabSectionIdGetErrors[keyof GetLeclabLeclabSectionIdGetErrors];

export type GetLeclabLeclabSectionIdGetResponses = {
    /**
     * Response Get Leclab Leclab  Section Id  Get
     *
     * Successful Response
     */
    200: Array<LecLabResponse>;
};

export type GetLeclabLeclabSectionIdGetResponse = GetLeclabLeclabSectionIdGetResponses[keyof GetLeclabLeclabSectionIdGetResponses];
