// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LecLab
 */
export type LecLab = {
    /**
     * Title
     */
    title?: string;
    /**
     * Type
     */
    type?: 'lecture' | 'laboratory' | null;
    /**
     * Prof
     */
    prof?: string;
    time?: Time;
};

/**
 * Rating
 */
export type Rating = {
    /**
     * Score
     */
    score?: number;
    /**
     * Avg
     */
    avg?: number;
    /**
     * Nrating
     */
    nRating?: number;
    /**
     * Takeagain
     */
    takeAgain?: number;
    /**
     * Difficulty
     */
    difficulty?: number;
    /**
     * Status
     */
    status?: 'found' | 'foundn\'t';
    /**
     * Prof
     */
    prof?: string;
    /**
     * Pid
     */
    pId?: string | null;
};

/**
 * Section
 */
export type Section = {
    /**
     * Id
     */
    id?: number;
    /**
     * Course
     */
    course?: string;
    /**
     * Section
     */
    section?: string;
    /**
     * Domain
     */
    domain?: string;
    /**
     * Code
     */
    code?: string;
    /**
     * Title
     */
    title?: string;
    /**
     * Times
     */
    times?: Array<LecLab>;
    /**
     * More
     */
    more?: string;
    viewData?: ViewData;
};

export type Time = {
    [key: string]: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ViewData = Array<{
    [key: string]: Array<number>;
}>;

export type GetSectionsSectionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Course
         */
        course?: string | null;
        /**
         * Domain
         */
        domain?: string | null;
        /**
         * Code
         */
        code?: string | null;
        /**
         * Title
         */
        title?: string | null;
        /**
         * Teacher
         */
        teacher?: string | null;
        /**
         * Min Rating
         */
        min_rating?: number | null;
        /**
         * Max Rating
         */
        max_rating?: number | null;
        /**
         * Min Score
         */
        min_score?: number | null;
        /**
         * Max Score
         */
        max_score?: number | null;
        /**
         * Days Off
         */
        days_off?: string | null;
        /**
         * Time Start
         */
        time_start?: string | null;
        /**
         * Time End
         */
        time_end?: string | null;
        /**
         * Blended
         */
        blended?: boolean;
        /**
         * Honours
         */
        honours?: boolean;
    };
    url: '/sections/';
};

export type GetSectionsSectionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSectionsSectionsGetError = GetSectionsSectionsGetErrors[keyof GetSectionsSectionsGetErrors];

export type GetSectionsSectionsGetResponses = {
    /**
     * Response Get Sections Sections  Get
     *
     * Successful Response
     */
    200: Array<Section>;
};

export type GetSectionsSectionsGetResponse = GetSectionsSectionsGetResponses[keyof GetSectionsSectionsGetResponses];

export type GetSectionSectionsSectionIdGetData = {
    body?: never;
    path: {
        /**
         * Section Id
         */
        section_id: number;
    };
    query?: never;
    url: '/sections/{section_id}';
};

export type GetSectionSectionsSectionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSectionSectionsSectionIdGetError = GetSectionSectionsSectionIdGetErrors[keyof GetSectionSectionsSectionIdGetErrors];

export type GetSectionSectionsSectionIdGetResponses = {
    /**
     * Successful Response
     */
    200: Section;
};

export type GetSectionSectionsSectionIdGetResponse = GetSectionSectionsSectionIdGetResponses[keyof GetSectionSectionsSectionIdGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRatingsRatingsProfGetData = {
    body?: never;
    path: {
        /**
         * Prof
         */
        prof: string;
    };
    query?: never;
    url: '/ratings/{prof}';
};

export type GetRatingsRatingsProfGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRatingsRatingsProfGetError = GetRatingsRatingsProfGetErrors[keyof GetRatingsRatingsProfGetErrors];

export type GetRatingsRatingsProfGetResponses = {
    /**
     * Response Get Ratings Ratings  Prof  Get
     *
     * Successful Response
     */
    200: Rating | null;
};

export type GetRatingsRatingsProfGetResponse = GetRatingsRatingsProfGetResponses[keyof GetRatingsRatingsProfGetResponses];
